### ISSUE TITLE
"release" command

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-dev-tool#10]
Workflow could be similar to ./build/build release from Yii 2.

**Comment by rugabarbo** [comment]
I think that such console commands need a separate namespace. For example, `maintenance:release` or something similar...

**Comment by samdark** [comment]
We're using / for namespacing.

**Comment by rugabarbo** [comment]
> We're using / for namespacing and I'm agree.

It seems that Symfony only supports the colon as a namespace delimiter :(

https://github.com/symfony/symfony/blob/12a8b6937b7d10c4067fc9f057ca85f4fdfc2729/src/Symfony/Component/Console/Command/Command.php#L652

**Comment by samdark** [comment]
Ww can adjust that.

**Comment by rugabarbo** [comment]
### The current implementation of commands in Yii2

#### `./build/build release/info --update`

1) If option `--update` is specified, executes command `git fetch --tags` in all packages
2) Executes command `git tag` for each package and fills version array with the result
3) Sorts the versions and removes alpha/beta versions from it
4) Calculates the next **PATCH** version for each package (`3.0.1` for `3.0.0`, `4.2.10` for `4.2.9` and so on).
5) Outputs the current and the next version for each package 

#### `./build/build release/release <package> --dryRun --version=x.x.x`

The framework release process will be shown (**for extensions and applications it is slightly different**).

1) If option `--dryRun` is specified, only prints info about potential actions, but doesn't change anything
2) Executes `git status --porcelain -uno` and throws an exception if there are uncommitted changes in the repository
3) Calculates the next **PATCH** version OR, if option `--version` is specified, uses an explicitly specified version for updating instead of the calculated one
4) Prints info about possible common errors before release and asks for confirmation to make changes
5) Asks if the correct branch is selected
6) Executes `git pull`
7) Executes `./build/build classmap/create` – it updates `./framework/classes.php` file
8) Executes `./build/build mime-type/index` – it updates `./framework/helpers/mime*.php` files
9) Executes `./build/build php-doc/fix` – it fixes PHPDoc style issues
10) Executes `./build/build php-doc/property` – it generates `@property` annotations in class files
11) Sorts `CHANGELOG.md` entries and replaces `under development` section with release info
12) Updates framework function `getVersion()` in the file `./framework/BaseYii.php`
13) Executes `git diff --color`, suggests to check the changes and asks for confirmation to continue
14) Prints a big message about the upcoming release :)
15) Suggests to check **GPG** settings (a release commit and tag should be signed) and asks for confirmation to continue
16) Executes:
    * `git commit -S -a -m "release version <version>"`
    * `git tag -s <version> -m "version <version>"`
    * `git push`
    * `git push --tags`
17) Prints a big congratulations message about the release :)
18) Prepares things for the next release:
    * adds `under development` section to `CHANGELOG.md`
    * updates framework function `getVersion()` in the file `./framework/BaseYii.php`
    * executes `git diff --color` 
    * executes `git commit -a -m "prepare for next release"`
    * executes `git push`
    * prints info about additional manual manipulations that need to be done after release

**Comment by samdark** [comment]
Additional thing to implement is making actual release at github such as https://github.com/yiisoft/friendly-exception/releases/tag/1.0.1. Note that description should contain version changelog from CHANGELOG.md.

**Comment by samdark** [comment]
Partially implemented. It's not doing GitHub releases yet.

**Comment by rustamwin** [comment]
After release:
- Create milestone of next release automatically?
